name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      - name: Delete PR Playground branch (if any)
        run: |
          git fetch origin
          git push origin --delete pr-${{ github.event.number }}-playground || echo "Branch does not exist"

      - name: Create new branch for Playground Preview
        run: git checkout -b pr-${{ github.event.number }}-playground

      - name: Install NPM Dependencies
        run: npm install

      - name: Install Composer Dependencies
        run: composer install

      - name: Run npm build
        run: npm run build

      - name: Add build files for Playground
        run: |
          git add -f build/
          git add -f vendor/

      - name: Commit build files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add build and vendors folders for PR ${{ github.event.number }}"

      - name: Share Playground detais on PR
        uses: actions/github-script@v7
        with:
            script: |
              const { owner, repo } = context.repo;
              const prNumber = context.payload.pull_request.number;

              const body = `WordPress Playground PR [Preview](https://playground.wordpress.net?plugin=https://github-proxy.com/proxy/?repo=ajitbohra/visual-blueprint-builder&branch=pr-${{github.event.number}}-playground)`
              
              const comments = await github.rest.issues.listComments({
                owner,
                repo,
                issue_number: prNumber,
               });

              const existing = comments.data.find(c => c.body.includes("WordPress Playground PR [Preview]"));
              
              if (existing) {
                await github.rest.issues.updateComment({
                  owner,
                  repo,
                  comment_id: existing.id,
                  body,
                });
              } else {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body,
                });
              }

      - name: Delete playground branch
        if: github.event_name == 'pull_request' && github.event.action == 'closed' || github.event_name == 'pull_request' && github.event.action == 'deleted'
        run: |
          git push origin --delete pr-${{ github.event.number }}-playground
